EasyDungeon1:
  World:
    “Survival”
  Restock time:
    Hours:
      24
    Minutes:
      00
  BossRoom:
    BossHealth:
      200
    BossDamage:
      5
    5x5RoomCorner1:
      X:
      Y:
      Z:
    5x5RoomCorner2:
      X:
      Y:
      Z:
  MobSpawnPoints:
    MobSpawnPoint1:
      X:
      Y:
      Z:
    MobSpawnPoint2:
      X:
      Y:
      Z:
    MobSpawnPoint3:
      X:
      Y:
      Z:
    MobSpawnPoint4:
      X:
      Y:
      Z:
    MobSpawnPoint5:
      X:
      Y:
      Z: